[theme]
primaryColor="#b17457"
backgroundColor="#faf7f0"
secondaryBackgroundColor="#d8d2c2"
textColor="#4a4947"

#primaryColor="#629584"
#backgroundColor="#243642"
#secondaryBackgroundColor="#387478"
#textColor="#E2F1E7"